name       : python-pbkdf2
version    : 1.3
release    : 6
source     :
    - https://pypi.python.org/packages/02/c0/6a2376ae81beb82eda645a091684c0b0becb86b972def7849ea9066e3d5e/pbkdf2-1.3.tar.gz : ac6397369f128212c43064a2b4878038dab78dab41875364554aaf2a684e6979
homepage   : https://www.dlitz.net/software/python-pbkdf2/
license    : MIT
component  : programming.python
summary    : This module implements the password-based key derivation function, PBKDF2, specified in RSA PKCS#5 v2.0
description: |
    This module implements the password-based key derivation function, PBKDF2, specified in RSA PKCS#5 v2.0.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
